In [ ]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [ ]:
#creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check no of dimensions of a tensor
scalar.ndim

0

In [ ]:
#creating vector
vector = tf.constant([10, 20])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>

In [ ]:
#dimension
vector.ndim

1

In [ ]:
#create matrix
matrix = tf.constant([[10, 7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#create another matrix
an_mat = tf.constant([[10, 7],
                      [3, 2],
                     [5, 9]], dtype = tf.float16)
an_mat


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 5.,  9.]], dtype=float16)>

In [ ]:
an_mat.ndim

2

In [ ]:
#lets create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                      [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

scalar is a single number
vector is a number with direction
matrix is a 2d array of numbers
tensor is an nd array of numbers (0d- scaler, 1d-vector)

In [ ]:
#creating variables
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#changing elements
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
#unchangeable_tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

In [ ]:
#creating random tensors
#random tensors are tensors with arbitrary Sized

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_1, random_2, random_1 == random_2

In [ ]:
#shuffle the order of elements in a tensor or shuffling a tensor
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [4, 5]])
not_shuffled.ndim

In [ ]:
not_shuffled

In [ ]:
#shuffle our non shuffle tensor
tf.random.shuffle(not_shuffled)

In [ ]:
tf.random.shuffle(not_shuffled)

In [ ]:
tf.random.shuffle(not_shuffled, seed=42)

It looks like if we want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as the operational level random seed.

Both seeds are used in conjunction to determine the random sequence.

In [ ]:
tf.random.set_seed(42) #global level random seed
tf.random.shuffle(not_shuffled, seed=42) #operational level random seed

In [ ]:
#other ways to make tensors.
#creating tensors of all ones
tf.ones([10, 7])

In [ ]:
tf.zeros(shape=(3, 4))

In [ ]:
#you can also turn NumPy arrays into tensors
#Tensors can be run on  GPU computing (diff btw tensors and numpy arrays)
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

#x = tf.constant(some_matrix) #captial for matrix or tensor
#y = tf.constant(vector) #non-captial for vector

In [ ]:
A =tf.constant(numpy_A, shape=(3, 8))
B = tf.constant(numpy_A)
A, B

In [ ]:
A.ndim

###Getting info from tensors
* Shape(length no of ele)
* Rank(dimensions)
* Axis or Dimension(particulr dim)
* Size(total no of items in the tensor)

In [ ]:
#create a rank 4 tensor(4 dim)
rank_4_t = tf.zeros(shape=[2, 3, 4, 5])
rank_4_t

In [ ]:
rank_4_t[0]

In [ ]:
rank_4_t.shape, rank_4_t.ndim, tf.size(rank_4_t)

In [ ]:
2 * 3 * 4 * 5

In [ ]:
#get various attributes of our tensor
print("Datatype of every ele:", rank_4_t.dtype)
print("No of dimensions(rank):", rank_4_t.ndim)
print("Shape of tensor:", rank_4_t.shape)
print("Elements along the 0 axis:", rank_4_t.shape[0])
print("Elements along the last axis:", rank_4_t.shape[-1])
print("Total no of elements in our tensor:", tf.size(rank_4_t))
print("Total no of elements in our tensor:", tf.size(rank_4_t))
print("Total no of elements in our tensor:", tf.size(rank_4_t).numpy())

Indexing tensors: tensors can be indexed just like python lists


In [ ]:
# get the first 2 elements of each dimension
rank_4_t[:2, :2, :2, :2]

In [ ]:
some_list = [1, 2, 3, 4]
some_list[:2]

In [ ]:
#get the 1st ele from each dim from each index except the final
rank_4_t[:1, :1, :1]

In [ ]:
rank_4_t.shape

In [ ]:
rank_4_t[:1, :1, :, :1]

In [ ]:
#create a rank  tensor with 3 dim
rank_2_t = tf.constant([[10, 7],
                        [3, 4]])
rank_2_t.shape, rank_2_t.ndim

In [ ]:
rank_2_t

In [ ]:
#get the last item
rank_2_t[:, -1]

In [ ]:
#adding an extra dim to our rank_2
rank_3_t = rank_2_t[..., tf.newaxis] #tf.newaxis is like none in numpy
rank_3_t

In [ ]:
#alternate to tf.newaxis
tf.expand_dims(rank_2_t, axis =-1) #-1 means expand the final ans

In [ ]:
tf.expand_dims(rank_2_t, axis =0) #expanding 0 axis

In [ ]:
rank_2_t

In [ ]:
#manipulating tensors(tensor operations)

#you can add values to the tensors through +noperator

t = tf.constant([[10, 7],
                 [3, 4]])
t+10

In [ ]:
#original tensor is unchanged
t

In [ ]:
# * operator
t * 10

In [ ]:
# - operator
t-10

In [ ]:
# we can use tf built in func

tf.multiply(t, 10)

In [ ]:
t

In [ ]:
tf.add(t, 10)

Matrix Multiplication:
In ml MM is one of the most common tensor operations
2 rules:
1. The inner dim must match
2. The resulting matrix has the shape of inner matrix

In [ ]:
t

In [ ]:
tf.matmul(t, t)

In [ ]:
#MM with @ operator
t*t, t@t

In [ ]:
#creating tensor of (3,2)
x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
x, y

In [ ]:
x @ y

In [ ]:
tf.matmul(x, y)

In [ ]:
y1 = tf.constant([[11, 12, 13],
                  [14, 14, 17]])
x @ y1

In [ ]:
y

In [ ]:
tf.reshape(y, shape=(2,3))

In [ ]:
x @ tf.reshape(y, shape=(2,3))

In [ ]:
x.shape,  tf.reshape(y, shape=(2,3)).shape

In [ ]:
tf.matmul(x, tf.reshape(y, shape=(2,3)))

In [ ]:
tf.matmul(tf.reshape(x, shape=(2, 3)), y)

In [ ]:
tf.transpose(x), tf.reshape(x, shape=(3, 2))

In [ ]:
#mm with transpose
tf.matmul(tf.transpose(x), x)

In [ ]:
# mm is referred to as the dot product
tf.tensordot(tf.transpose(x), y, axes=1) # should specify axes

In [ ]:
tf.matmul(x, tf.transpose(y))

In [ ]:
y, tf.transpose(y), tf.reshape(y, shape=(2, 3))

In [ ]:
# changing datatype
b = tf.constant([7, 10])
b.dtype

In [ ]:
c = tf.constant([7.0, 8.5])
c.dtype

In [ ]:
b1 = tf.cast(b, dtype=tf.float32)
b1.dtype

In [ ]:
c1 = tf.cast(c, dtype=tf.int32)
c1.dtype

In [ ]:
b11 = tf.cast(b1, dtype=tf.float16)
b11.dtype

Aggregating *Tensors* Multiple values down to smaller values
Minimum
Maximum
Mean
Sum

In [ ]:
#get absolute values
d = tf.constant([-7, -10])
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
#random tensor
import numpy as np
e = tf.constant(np.random.randint(0, 100, size=50))
e

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([60, 13, 31, 22, 92, 34, 41, 57, 34, 88, 11, 62, 57, 38, 17, 30,  1,
       53, 88, 64, 83, 76, 97, 34, 81, 47, 41, 45, 62, 25, 61, 51,  2, 55,
       16, 18, 22, 69, 71, 81, 18, 47, 33, 87, 46,  2, 93, 60, 88, 13])>

In [ ]:
#Finding minimum
tf.reduce_min(e)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
#finding maximum
tf.reduce_max(e)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [ ]:
#mean
tf.reduce_mean(e)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [ ]:
#finding sum
tf.reduce_sum(e)

<tf.Tensor: shape=(), dtype=int64, numpy=2417>

In [ ]:
#variance
import tensorflow_probability as tfp
tfp.stats.variance(e)

<tf.Tensor: shape=(), dtype=int64, numpy=735>

In [ ]:
tf.math.reduce_variance(tf.cast(e, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=734.98444>

In [ ]:
#standard deviation
tf.math.reduce_std(tf.cast(e, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.110596>

In [ ]:
#find positional maximum and minimum
tf.random.set_seed(42)
f = tf.random.uniform(shape=[50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmax(f)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
#index on our larget value
f[tf.argmax(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
f[tf.argmax(f)]==tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
tf.argmin(f)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
f[tf.argmin(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

One-hot encoding tensors

In [ ]:
list = [0, 1, 2, 3]
tf.one_hot(list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#specifing custom values
tf.one_hot(list, depth=4, on_value="yo I love deep learning", off_value="I also like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love deep learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'yo I love deep learning',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'yo I love deep learning', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'yo I love deep learning']],
      dtype=object)>

Tensors and NumPY

In [ ]:
j = tf.constant(np.array([3, 4, 5, 6]))
j

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([3, 4, 5, 6])>

In [ ]:
np.array(j), type(np.array(j))

(array([3, 4, 5, 6]), numpy.ndarray)

In [ ]:
j.numpy(), type(j.numpy())

(array([3, 4, 5, 6]), numpy.ndarray)

In [ ]:
a = "alekhya"
a

'alekhya'